name = "HyperQL"
grammar = "hyperql"
path_suffixes = ["hql", "hyperql"]
file_types = ["hql", "hyperql"]
line_comments = ["//", "--"]

[[brackets]]
start = "("
end = ")"
close = true
newline = true

[[brackets]]
start = "["
end = "]"
close = true
newline = true

[[brackets]]
start = "{"
end = "}"
close = true
newline = true

[[brackets]]
start = "\""
end = "\""
close = true
newline = false
