id = "hyperql"
name = "HyperQL"
version = "0.1.1"
schema_version = 1
authors = ["jarbear82"]
description = "HyperQL support for Zed"
repository = "https://github.com/jarbear82/hyperql"

[grammars.hyperql]
repository = "file:///home/jarbear82/Documents/tree-sitter/tree-sitter-hyperql"
rev = "b1c181c65cd9087e6c42b03d0675a5d9dec3a932"

[language_servers.hyperql]
name = "hyperql-lsp"
languages = ["HyperQL"]
