id = "hyperql"
name = "HyperQL"
version = "0.1.1"
schema_version = 1
authors = ["jarbear82"]
description = "HyperQL support for Zed"
repository = "https://github.com/jarbear82/hyperql"

[grammars.hyperql]
repository = "file:///home/jarbear82/Documents/hyperql/tree-sitter-hyperql"
rev = "17712d4328ca5c3a3081c9e86f1a3b8ea235c90d"

[language_servers.hyperql]
name = "hyperql-lsp"
languages = ["HyperQL"]
