id = "hyperql"
name = "HyperQL"
version = "0.1.0"
schema_version = 1
authors = ["jarbear82"]
description = "HyperQL support for Zed"
repository = "https://github.com/jarbear82/hyperql"

[grammars.hyperql]
repository = "https://github.com/jarbear82/hyperql"
commit = "ba6571c0ffabb67f42888a67b580fa0b4b901142"