id = "hyperql"
name = "HyperQL"
version = "0.1.0"
schema_version = 1
authors = ["jarbear82"]
description = "HyperQL support for Zed"
repository = "https://github.com/jarbear82/hyperql"

[grammars.hyperql]
repository = "file:///home/jarbear82/Documents/tree-sitter/tree-sitter-hyperql"
rev = "489b973faca37b7e4333dff85ae1225b260bbc9e"